# Generated by Django 3.2.12 on 2022-02-11 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0002_auto_20220211_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_base_transaction',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='data_base_transaction',
            name='sender',
        ),
    ]
